apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-events
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-events
  template:
    metadata:
      labels:
        app: customer-events
    spec:
      containers:
        - image: cmidhun/customer-events:0.0.1-SNAPSHOT
          name: customer-events
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            resources:
              requests:
                memory: "50Mi"
                cpu: "500m"
              limits:
                memory: "500Mi"
                cpu: "2000m"
