apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-events-master
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-events-master
  template:
    metadata:
      labels:
        app: customer-events-master
    spec:
      containers:
        - image: cmidhun/customer-events-master:0.1.0-SNAPSHOT
          name: customer-events-master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
